### ISSUE TITLE
Docker still supported?

### ISSUE THREAD

**Issue by Svarto** [wazuh/docker-ossec#3]
Hi!

I want to install wazuh and hopefully through docker, but I saw that the docker github repository hasn't been updated in awhile while your wazuh blog posted a new version release not so long time ago.

Just wondered if the docker is still supported?

Thanks a lot!

**Comment by Svarto** [comment]
thank you so much!

**Comment by mjflve** [comment]
Anytime, please not hesitate to contact us again. We're glad to help.
